apiVersion: v1
kind: Secret
metadata:
  name: {{.AddonName}}
  labels:
    app: {{.AppName}}
    apps: {{.AddonName}}
type: Opaque
data:
  rabbitmq-erlang-cookie: YXBwc1Jvb3RQd2Q=
  rabbitmq-password: YXBwc1B3ZA==
---
apiVersion: v1
kind: Service
metadata:
  name: {{.AddonName}}
  labels:
    app: {{.AppName}}
    apps: {{.AddonName}}
spec:
  type: NodePort
  ports:
  - name: epmd
    port: 4369
    targetPort: epmd
  - name: amqp
    port: 5672
    targetPort: amqp
  - name: dist
    port: 25672
    targetPort: dist
  - name: stats
    port: 15672
    targetPort: stats
  selector:
    apps: {{.AddonName}}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.AddonName}}-rabbitmq-pv-claim
  labels:
    app: {{.AppName}}
    apps: {{.AddonName}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: "standard"
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{.AddonName}}
  labels:
    app: {{.AppName}}
    apps: {{.AddonName}}
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: {{.AddonName}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        apps: {{.AddonName}}
    spec:
      containers:
      - name: {{.AddonName}}
        image: "bitnami/rabbitmq:latest"
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
        env:
        - name: RABBITMQ_USERNAME
          value: "apps"
        - name: RABBITMQ_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{.AddonName}}
              key: rabbitmq-password
        - name: RABBITMQ_ERL_COOKIE
          valueFrom:
            secretKeyRef:
              name: {{.AddonName}}
              key: rabbitmq-erlang-cookie
        ports:
        - name: epmd
          containerPort: 4369
        - name: amqp
          containerPort: 5672
        - name: dist
          containerPort: 25672
        - name: stats
          containerPort: 15672
        volumeMounts:
        - name: data
          mountPath: /bitnami/rabbitmq
        livenessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 120
          timeoutSeconds: 5
          failureThreshold: 6
        readinessProbe:
          exec:
            command:
            - rabbitmqctl
            - status
          initialDelaySeconds: 10
          timeoutSeconds: 3
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: {{.AddonName}}-rabbitmq-pv-claim    
